Move the rsync/overlay actions prior to any 2nd stage (they are useful for sb2 and probably lxc)
Signed-off-by: David Greaves <david@dgreaves.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1065,6 +1065,38 @@ for RECIPEFILE in "${RECIPEFILES[@]}" ; do
 	fi
     fi
 
+    # Do the overlay and rsync before entering any lxc or chroot
+    if test -n "$OVERLAY" ; then
+	if test -d "$OVERLAY"; then
+	    pushd $OVERLAY
+	    echo "Copying overlay to BUILD_TARGET"
+	    tar -cpf - . | (cd $BUILD_TARGET ; tar -xvf -)
+	    popd
+	else
+	    echo "OVERLAY ($OVERLAY) is no directory - skipping"
+	fi
+    fi
+
+    if test -n "$RSYNCSRC" ; then
+	if test -n "$RSYNCDEST" ; then
+	    if test -d "$RSYNCSRC" ; then
+		if ! test -d "$BUILD_TARGET/$RSYNCDEST" ; then
+		    echo "ATTENTION! Creating missing target directory ($BUILD_TARGET/$RSYNCDEST)."
+		    mkdir -p $BUILD_TARGET/$RSYNCDEST
+		fi
+		echo "Running rsync ..."
+		rsync -av $RSYNCSRC/* $BUILD_TARGET/$RSYNCDEST/
+		chown -R "$ABUILD_UID:$ABUILD_GID" "$BUILD_TARGET/$RSYNCDEST"
+		RSYNCDONE=true
+		echo "... done"
+	    else
+		echo "RSYNCSRC is not a directory - skipping"
+	    fi
+	else
+	    echo "RSYNCSRC given, but not RSYNCDEST - skipping"
+	fi
+    fi
+
     if test -n "$VM_TYPE" -a -z "$RUNNING_IN_VM"; then
 	vm_first_stage
 	cleanup_and_exit 0
@@ -1249,37 +1281,6 @@ for RECIPEFILE in "${RECIPEFILES[@]}" ; do
     echo -----------------------------------------------------------------
     echo -----------------------------------------------------------------
     BUILD_SUCCEEDED=false
-
-    if test -n "$OVERLAY" ; then
-	if test -d "$OVERLAY"; then
-	    pushd $OVERLAY
-	    echo "Copying overlay to BUILD_TARGET"
-	    tar -cpf - . | (cd $BUILD_TARGET ; tar -xvf -)
-	    popd
-	else
-	    echo "OVERLAY ($OVERLAY) is no directory - skipping"
-	fi
-    fi
-
-    if test -n "$RSYNCSRC" ; then
-	if test -n "$RSYNCDEST" ; then
-	    if test -d "$RSYNCSRC" ; then
-		if ! test -d "$BUILD_TARGET/$RSYNCDEST" ; then
-		    echo "ATTENTION! Creating missing target directory ($BUILD_TARGET/$RSYNCDEST)."
-		    mkdir -p $BUILD_TARGET/$RSYNCDEST
-		fi
-		echo "Running rsync ..."
-		rsync -av $RSYNCSRC/* $BUILD_TARGET/$RSYNCDEST/
-		chown -R "$ABUILD_UID:$ABUILD_GID" "$BUILD_TARGET/$RSYNCDEST"
-		RSYNCDONE=true
-		echo "... done"
-	    else
-		echo "RSYNCSRC is not a directory - skipping"
-	    fi
-	else
-	    echo "RSYNCSRC given, but not RSYNCDEST - skipping"
-	fi
-    fi
 
     if test "$DO_BUILD" = false ; then
 	echo "Not doing build as requested"
