Add support for using Scratchbox2 together with OBS as an alternative cross compile approach
Signed-off-by: Carsten Munk <carsten.munk@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -40,7 +40,7 @@ test -z "$BUILD_DIR" && BUILD_DIR=/usr/lib/build
 test -z "$BUILD_ROOT" && BUILD_ROOT=/var/tmp/build-root
 test -z "$CONFIG_DIR" && CONFIG_DIR="$BUILD_DIR/configs"
 
-export BUILD_ARCH BUILD_HOST_ARCH BUILD_ROOT BUILD_RPMS BUILD_DIR BUILD_DEBUG
+export BUILD_ARCH BUILD_HOST_ARCH BUILD_TARGET BUILD_ROOT BUILD_SB2FLAGS BUILD_RPMS BUILD_DIR BUILD_DEBUG VM_TYPE
 export BUILD_DIST
 
 icecream=0
@@ -424,6 +424,7 @@ cleanup_and_exit () {
     if test -n "$RUNNING_IN_VM" ; then
 	echo "$1" >  /.build/_exitcode
 	test -n "$browner" && chown "$browner" $BUILD_ROOT
+	cleanup_sb2
 	vm_shutdown "$1"
     else
 	umount -n $BUILD_ROOT/proc/sys/fs/binfmt_misc 2> /dev/null || true
@@ -494,7 +495,7 @@ setupicecream() {
 	return 0
     fi
 
-    if ! chroot "$BUILD_ROOT" rpm -q icecream >/dev/null 2>/dev/null; then
+    if ! enter_target needroot rpm -q icecream >/dev/null 2>/dev/null; then
 	echo "*** icecream package not installed ***"
 	return 1
     fi
@@ -532,7 +533,7 @@ setupicecream() {
 	    return 1
 	fi
         echo "creating new env in '$icecreamdir'"
-	chroot $BUILD_ROOT bash -c "cd $icecreamdir; $createenv" || cleanup_and_exit 1
+	enter_target needroot bash -c "cd $icecreamdir; $createenv" || cleanup_and_exit 1
 	icecc_vers=(`shopt -s nullglob; echo $BUILD_ROOT/$icecreamdir/*.tar.{bz2,gz}`)
 	icecc_vers=${icecc_vers//$BUILD_ROOT/}
 	echo "created icecream environment $icecc_vers"
@@ -582,7 +583,7 @@ create_baselibs() {
 	if test -e $BUILD_ROOT$TOPDIR/SOURCES/baselibs.conf ; then
 	    BASELIBS_CFG="-c $TOPDIR/SOURCES/baselibs.conf"
 	fi
-	if test -e $BUILD_ROOT/usr/lib/build/baselibs_global.conf; then
+	if test -e $BUILD_TARGET/usr/lib/build/baselibs_global.conf; then
 	    BASELIBS_GLOBAL="-c /usr/lib/build/baselibs_global.conf"
 	fi
 	pkgs=($RPMS)
@@ -596,7 +597,7 @@ create_baselibs() {
     # $BUILD_DIR is set to /.build when using a vm. So we need to
     # hardcode /usr/lib/build instead of $BUILD_DIR to prefer
     # mkbaselibs from the distro.
-    if test -f $BUILD_ROOT$mkbaselibs; then
+    if test -f $BUILD_TARGET$mkbaselibs; then
 	if test -z "$BASELIBS_CFG" -a -e $BUILD_ROOT/usr/lib/build/baselibs.conf ; then
 	    BASELIBS_CFG="-c /usr/lib/build/baselibs.conf"
 	fi
@@ -608,28 +609,28 @@ create_baselibs() {
 	# use external version
 	whichone=" (external)"
 	mkbaselibs="/.mkbaselibs/mkbaselibs"
-	rm -rf "$BUILD_ROOT/.mkbaselibs"
-	mkdir -p "$BUILD_ROOT/.mkbaselibs"
-	cp -f $BUILD_DIR/mkbaselibs $BUILD_ROOT/.mkbaselibs/
+	rm -rf "$BUILD_TARGET/.mkbaselibs"
+	mkdir -p "$BUILD_TARGET/.mkbaselibs"
+	cp -f $BUILD_DIR/mkbaselibs $BUILD_TARGET/.mkbaselibs/
 	if test "$BUILDTYPE" == "dsc" ; then
-	    cp -f $BUILD_DIR/baselibs_global-deb.conf $BUILD_ROOT/.mkbaselibs/baselibs_g.conf
-	    cp -f $BUILD_ROOT$TOPDIR/SOURCES/baselibs-deb.conf $BUILD_ROOT/.mkbaselibs/baselibs-deb.conf
+	    cp -f $BUILD_DIR/baselibs_global-deb.conf $BUILD_TARGET/.mkbaselibs/baselibs_g.conf
+	    cp -f $BUILD_ROOT$TOPDIR/SOURCES/baselibs-deb.conf $BUILD_TARGET/.mkbaselibs/baselibs-deb.conf
 	    BASELIBS_CFG="-c /.mkbaselibs/baselibs-deb.conf"
 	else
-	    cp -f $BUILD_DIR/baselibs_global.conf $BUILD_ROOT/.mkbaselibs/baselibs_g.conf
+	    cp -f $BUILD_DIR/baselibs_global.conf $BUILD_TARGET/.mkbaselibs/baselibs_g.conf
 	    if test -z "$BASELIBS_CFG" -a -e $BUILD_DIR/baselibs.conf; then
-		cp -f $BUILD_DIR/baselibs.conf $BUILD_ROOT/.mkbaselibs/baselibs.conf
+		cp -f $BUILD_DIR/baselibs.conf $BUILD_TARGET/.mkbaselibs/baselibs.conf
 		BASELIBS_CFG="-c /.mkbaselibs/baselibs.conf"
 	    fi
 	fi
-	if test -e $BUILD_ROOT/.mkbaselibs/baselibs_g.conf; then
+	if test -e $BUILD_TARGET/.mkbaselibs/baselibs_g.conf; then
 	    BASELIBS_GLOBAL="-c /.mkbaselibs/baselibs_g.conf"
 	fi
     fi
     echo "... creating baselibs$whichone"
     while read line
     do
-	chroot $BUILD_ROOT su -c "$mkbaselibs $BASELIBS_GLOBAL $BASELIBS_CFG $line" - $BUILD_USER || cleanup_and_exit 1
+	enter_target needuser $mkbaselibs $BASELIBS_GLOBAL $BASELIBS_CFG $line || cleanup_and_exit 1
     done < <(IFS=$'\n'; echo "${pkgs[*]#$BUILD_ROOT}" | xargs -n 1024)
     rm -rf "$BUILD_ROOT/.mkbaselibs"
 }
@@ -640,11 +641,11 @@ copy_oldpackages() {
     local dest
     test -z "$RUNNING_IN_VM" || return 0
     if test -z "$old_packages" ; then
-	rm -rf "$BUILD_ROOT"/.build.oldpackages*
+	rm -rf "$BUILD_TARGET"/.build.oldpackages*
 	return 0
     fi
     for d in "${old_packages[@]}"; do
-	dest="$BUILD_ROOT/.build.oldpackages"
+	dest="$BUILD_TARGET/.build.oldpackages"
 	test "$i" = 0 || dest="$dest$i"
 	if test -d "$d" -a "$d" != "$dest" ; then
 	    rm -rf "$dest"
@@ -685,8 +686,8 @@ mkdir_build_root() {
 copy_overlay() {
     if test -d "$OVERLAY"; then
 	pushd $OVERLAY
-	echo "Copying overlay to BUILD_ROOT"
-	tar -cpf - . | (cd $BUILD_ROOT ; tar -xvf -)
+	echo "Copying overlay to BUILD_TARGET"
+	tar -cpf - . | (cd $BUILD_TARGET ; tar -xvf -)
 	popd
     else
 	echo "OVERLAY ($OVERLAY) is no directory - skipping"
@@ -696,13 +697,13 @@ copy_overlay() {
 run_rsync() {
     if test -n "$RSYNCDEST" ; then
 	if test -d "$RSYNCSRC" ; then
-	    if ! test -d "$BUILD_ROOT/$RSYNCDEST" ; then
-		echo "ATTENTION! Creating missing target directory ($BUILD_ROOT/$RSYNCDEST)."
-		mkdir -p $BUILD_ROOT/$RSYNCDEST
+	    if ! test -d "$BUILD_TARGET/$RSYNCDEST" ; then
+		echo "ATTENTION! Creating missing target directory ($BUILD_TARGET/$RSYNCDEST)."
+		mkdir -p $BUILD_TARGET/$RSYNCDEST
 	    fi
 	    echo "Running rsync ..."
-	    rsync -av $RSYNCSRC/* $BUILD_ROOT/$RSYNCDEST/
-	    chown -R "$ABUILD_UID:$ABUILD_GID" "$BUILD_ROOT/$RSYNCDEST"
+	    rsync -av $RSYNCSRC/* $BUILD_TARGET/$RSYNCDEST/
+	    chown -R "$ABUILD_UID:$ABUILD_GID" "$BUILD_TARGET/$RSYNCDEST"
 	    RSYNCDONE=true
 	    echo "... done"
 	else
@@ -1068,6 +1069,15 @@ if test -n "$DO_WIPE" ; then
     cleanup_and_exit
 fi
 
+set_build_arch
+
+BUILD_SB2FLAGS=`getsb2flags --dist "$BUILD_DIST" --configdir "$BUILD_DIR/configs" --archpath "$BUILD_ARCH"`
+
+if [ -n "$BUILD_SB2FLAGS" -a -z "$VM_TYPE" ]; then
+    echo "Cannot do SB2 with chroot, switching to vm type sb2"
+    VM_TYPE="sb2"
+fi
+
 if test -n "$KILL" ; then
     kill_running_build
     cleanup_and_exit
@@ -1091,7 +1101,18 @@ else
     repos=()
 fi
 
-set_build_arch
+
+BUILD_TARGET=$BUILD_ROOT
+
+if [ -n "$BUILD_SB2FLAGS" ]; then
+	echo "Will build with SB2, flags: $BUILD_SB2FLAGS"
+	echo "Switching BUILD_TARGET to $BUILD_ROOT/target"
+	if test -z "$RUNNING_IN_VM"; then
+		BUILD_TARGET=$BUILD_ROOT/target
+	else
+		BUILD_TARGET=/target
+	fi
+fi
 
 expand_recipe_directories
 
@@ -1116,6 +1137,10 @@ if test -z "$RUNNING_IN_VM" -a -n "$VM_TYPE" -a -n "$VM_ROOT" ; then
 fi
 
 mkdir_build_root
+
+if test "$BUILD_ROOT" != "$BUILD_TARGET" ; then
+	mkdir -p "$BUILD_TARGET"
+fi
 
 if test "$BUILD_ROOT" = / ; then
     browner="$(stat -c %u /)"
@@ -1166,6 +1191,7 @@ test -z "$HOST" && HOST=`hostname`
 
 if test -z "$RUNNING_IN_VM" ; then
     echo Using BUILD_ROOT=$BUILD_ROOT
+    echo Using BUILD_TARGET=$BUILD_TARGET
     test -n "$BUILD_RPMS" && echo Using BUILD_RPMS=$BUILD_RPMS
     echo Using BUILD_ARCH=$BUILD_ARCH
     test -n "$VM_TYPE" && echo "Doing $VM_TYPE build${VM_ROOT:+ in $VM_ROOT}"
@@ -1292,8 +1318,8 @@ for RECIPEFILE in "${RECIPEFILES[@]}" ; do
     # check if we want to build with the abuild user
     #
     BUILD_USER=abuild
-    if test -x $BUILD_ROOT/bin/rpm ; then
-	SUSE_VERSION=`chroot $BUILD_ROOT /bin/rpm --eval '%{?suse_version}' 2>/dev/null`
+    if test -x $BUILD_TARGET/bin/rpm ; then
+	SUSE_VERSION=`enter_target needroot /bin/rpm --eval '%{?suse_version}' 2>/dev/null`
 	test -n "$SUSE_VERSION" -a "${SUSE_VERSION:-0}" -le 1020 && BUILD_USER=root
     fi
     if test "$BUILD_USER" = abuild ; then
@@ -1315,49 +1341,49 @@ for RECIPEFILE in "${RECIPEFILES[@]}" ; do
 
     # fixup passwd/group
     if test $BUILD_USER = abuild ; then
-	if ! egrep '^abuild:' >/dev/null <$BUILD_ROOT/etc/passwd ; then
-	    echo "abuild:x:${ABUILD_UID}:${ABUILD_GID}:Autobuild:/home/abuild:/bin/bash" >>$BUILD_ROOT/etc/passwd
-	    echo 'abuild:*:::::::' >>$BUILD_ROOT/etc/shadow # This is needed on Mandriva 2009
-	    echo 'abuild:*::' >>$BUILD_ROOT/etc/gshadow # This is needed on Ubuntu
-	    echo "abuild:x:${ABUILD_GID}:" >>$BUILD_ROOT/etc/group
+	if ! egrep '^abuild:' >/dev/null <$BUILD_TARGET/etc/passwd ; then
+	    echo "abuild:x:${ABUILD_UID}:${ABUILD_GID}:Autobuild:/home/abuild:/bin/bash" >>$BUILD_TARGET/etc/passwd
+	    echo 'abuild:*:::::::' >>$BUILD_TARGET/etc/shadow # This is needed on Mandriva 2009
+	    echo 'abuild:*::' >>$BUILD_TARGET/etc/gshadow # This is needed on Ubuntu
+	    echo "abuild:x:${ABUILD_GID}:" >>$BUILD_TARGET/etc/group
 	    mkdir -p $BUILD_ROOT/home/abuild
 	    chown "$ABUILD_UID:$ABUILD_GID" $BUILD_ROOT/home/abuild
 	else
-	    if ! egrep "^abuild:x?:${ABUILD_UID}:${ABUILD_GID}" >/dev/null <$BUILD_ROOT/etc/passwd ; then
-		echo "abuild user present in the buildroot ($BUILD_ROOT) but uid:gid does not match"
+	    if ! egrep "^abuild:x?:${ABUILD_UID}:${ABUILD_GID}" >/dev/null <$BUILD_TARGET/etc/passwd ; then
+		echo "abuild user present in the build target ($BUILD_TARGET) but uid:gid does not match"
 		echo "buildroot currently using:"
-		egrep "^abuild:" <$BUILD_ROOT/etc/passwd
+		egrep "^abuild:" <$BUILD_TARGET/etc/passwd
 		echo "build script attempting to use:"
 		echo "abuild::${ABUILD_UID}:${ABUILD_GID}:..."
 		echo "build aborting"
 		cleanup_and_exit 1
 	    fi
 	fi
-	if test -f $BUILD_ROOT/etc/shadow ; then
-	    sed -i -e "s@^root::@root:*:@" $BUILD_ROOT/etc/shadow
+	if test -f $BUILD_TARGET/etc/shadow ; then
+	    sed -i -e "s@^root::@root:*:@" $BUILD_TARGET/etc/shadow
 	fi
-	if test -f $BUILD_ROOT/etc/gshadow ; then
-	    sed -i -e "s@^root::@root:*:@" $BUILD_ROOT/etc/gshadow
+	if test -f $BUILD_TARGET/etc/gshadow ; then
+	    sed -i -e "s@^root::@root:*:@" $BUILD_TARGET/etc/gshadow
 	fi
 	BUILD_USER_ABUILD_USED=true
     else
 	# building as root
 	ABUILD_UID=0
 	ABUILD_GID=0
-	if egrep '^abuild:' >/dev/null <$BUILD_ROOT/etc/passwd ; then
+	if egrep '^abuild:' >/dev/null <$BUILD_TARGET/etc/passwd ; then
 	    rm -rf "$BUILD_ROOT/home/abuild"
-	    sed -i -e '/^abuild:/d' $BUILD_ROOT/etc/passwd
-	    sed -i -e '/^abuild:/d' $BUILD_ROOT/etc/group
-	    if test -f $BUILD_ROOT/etc/shadow ; then
-		sed -i -e '/^abuild:/d' $BUILD_ROOT/etc/shadow
+	    sed -i -e '/^abuild:/d' $BUILD_TARGET/etc/passwd
+	    sed -i -e '/^abuild:/d' $BUILD_TARGET/etc/group
+	    if test -f $BUILD_TARGET/etc/shadow ; then
+		sed -i -e '/^abuild:/d' $BUILD_TARGET/etc/shadow
 	    fi
-	    if test -f $BUILD_ROOT/etc/gshadow ; then
-		sed -i -e '/^abuild:/d' $BUILD_ROOT/etc/gshadow
+	    if test -f $BUILD_TARGET/etc/gshadow ; then
+		sed -i -e '/^abuild:/d' $BUILD_TARGET/etc/gshadow
 	    fi
 	fi
     fi
 
-    if test -n "$RUNNING_IN_VM" ; then
+    if test -n "$RUNNING_IN_VM" -a "$VM_TYPE" != "sb2" ; then
 	vm_setup_network
     fi
 
@@ -1468,7 +1494,7 @@ if test -n "$RPMS" -a -n "$BUILD_USER_ABUILD_USED" ; then
     recipe_check_file_owners
 fi
 
-if test -n "$RPMS" -a -d "$BUILD_ROOT/usr/lib/build/checks" ; then
+if test -n "$RPMS" -a -d "$BUILD_TARGET/usr/lib/build/checks" ; then
     export DO_RPM_REMOVE=true
     # workaround for broken 13.1 check scripts which umount /proc
     if test -n "$RUNNING_IN_VM" -a "$BUILD_ROOT" = / ; then
@@ -1479,7 +1505,7 @@ if test -n "$RPMS" -a -d "$BUILD_ROOT/usr/lib/build/checks" ; then
     for SRPM in $BUILD_ROOT/$TOPDIR/SRPMS/*src.rpm ; do
 	test -f "$SRPM" && PNAME=`rpm --nodigest --nosignature -qp --qf "%{NAME}" $SRPM`
     done
-    for CHECKSCRIPT in $BUILD_ROOT/usr/lib/build/checks/* ; do
+    for CHECKSCRIPT in $BUILD_TARGET/usr/lib/build/checks/* ; do
 	echo "... running ${CHECKSCRIPT##*/}"
 	$CHECKSCRIPT || cleanup_and_exit 1
     done
@@ -1503,7 +1529,7 @@ exitcode=0
 
 # post build work
 # TODO: don't hardcode. instead run scripts in a directory as it's done for the checks
-if test -n "$RPMS" -a -d "$BUILD_ROOT/.build.oldpackages" ; then
+if test -n "$RPMS" -a -d "$BUILD_TARGET/.build.oldpackages" ; then
     recipe_compare_oldpackages
     # no need to create deltas if the build is the same
     if test ! -e $BUILD_ROOT/.build/.same_result_marker ; then
